
services:
  db:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - arn-postgres-data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - db

  minio:
    image: minio/minio:RELEASE.2025-09-01T00-00-00Z
    container_name: minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"    # API
      - "9001:9001"    # Консоль
    command: server /data --console-address ":9001"

volumes:
  arn-postgres-data:
